[package]
name = "merkleberg"
version = "0.1.0"
authors = ["Erica Marigold <hi@devcomp.xyz> ", "Nervos Core Dev <dev@nervos.org>"]
documentation = "https://docs.rs/merkleberg"
edition = "2024"
homepage = "https://pesde.dev/"
rust-version = "1.85.0"
license = "MIT"
description = "Merkle mountain range library in Rust"
repository = "https://github.com/pesde-pkg/merkleberg"

[features]
default = ["std", "digest"]
std = ["thiserror/std"]
digest = ["dep:digest"]
unsafe-digest = ["digest"]
serde = ["dep:serde"]

[dependencies]
cfg-if = "1.0"
futures-util = "0.3"
digest = { version = "0.11", optional = true }
thiserror = { version = "2.0", default-features = false }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
faster-hex = "0.8.0"
criterion = "0.5.1"
rand = "0.8.5"
proptest = "1.2.0"
lazy_static = "1.4.0"
bytes = "1.4.0"
blake2b-rs = "0.2.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sha2 = "0.11"

[[bench]]
name = "mmr_benchmark"
harness = false

[[bench]]
name = "helper_benchmark"
harness = false

[[bench]]
name = "mmriver_benchmark"
harness = false

[lints.clippy]
zero_sized_map_values = "warn"
while_float = "deny"
useless_let_if_seq = "warn"
unused_trait_names = "warn"
unused_result_ok = "warn"
unused_peekable = "warn"
unused_async = "warn"
unreadable_literal = "warn"
unnested_or_patterns = "warn"
unneeded_field_pattern = "warn"
unnecessary_wraps = "warn"
unnecessary_semicolon = "warn"
unnecessary_self_imports = "warn"
unnecessary_literal_bound = "warn"
unnecessary_join = "warn"
unnecessary_box_returns = "warn"
uninlined_format_args = "warn"
type_repetition_in_bounds = "warn"
try_err = "warn"
trivially_copy_pass_by_ref = "warn"
trait_duplication_in_bounds = "warn"
todo = "deny"
suspicious_operation_groupings = "warn"
suboptimal_flops = "deny"
struct_field_names = "warn"
string_lit_chars_any = "warn"
string_lit_as_bytes = "warn"
str_split_at_newline = "warn"
stable_sort_primitive = "warn"
single_option_map = "warn"
single_match_else = "warn"
single_char_pattern = "warn"
#significant_drop_tightening = "warn"
significant_drop_in_scrutinee = "warn"
set_contains_or_insert = "deny"
separated_literal_suffix = "warn"
semicolon_inside_block = "warn"
semicolon_if_nothing_returned = "warn"
self_named_module_files = "warn"
same_functions_in_if_condition = "warn"
return_and_then = "warn"
renamed_function_params = "warn"
ref_patterns = "deny"
ref_option = "deny"
ref_binding_to_reference = "deny"
redundant_type_annotations = "deny"
redundant_else = "warn"
redundant_closure_for_method_calls = "warn"
redundant_clone = "deny"
read_zero_byte_vec = "warn"
rc_buffer = "deny"
range_plus_one = "deny"
range_minus_one = "deny"
pub_without_shorthand = "deny"
pub_underscore_fields = "deny"
precedence_bits = "deny"
pathbuf_init_then_push = "warn"
path_buf_push_overwrite = "warn"
option_option = "deny"
option_as_ref_cloned = "deny"
nonstandard_macro_braces = "deny"
non_zero_suggestions = "deny"
no_effect_underscore_binding = "warn"
needless_raw_string_hashes = "warn"
needless_pass_by_value = "deny"
needless_pass_by_ref_mut = "warn"
needless_for_each = "deny"
needless_continue = "deny"
needless_collect = "deny"
needless_bitwise_bool = "deny"
mut_mut = "deny"
must_use_candidate = "warn"
maybe_infinite_iter = "deny"
match_wildcard_for_single_variants = "deny"
match_bool = "warn"
map_unwrap_or = "warn"
map_err_ignore = "warn"
manual_midpoint = "warn"
manual_let_else = "warn"
manual_is_variant_and = "warn"
manual_is_power_of_two = "warn"
lossy_float_literal = "deny"
literal_string_with_formatting_args = "warn"
large_types_passed_by_value = "warn"
large_stack_frames = "warn"
large_stack_arrays = "warn"
large_digit_groups = "deny"
iter_with_drain = "deny"
iter_on_single_items = "deny"
iter_on_empty_collections = "deny"
iter_filter_is_some = "deny"
iter_filter_is_ok = "deny"
invalid_upcast_comparisons = "deny"
integer_division = "deny"
infinite_loop = "deny"
inefficient_to_string = "warn"
index_refutable_slice = "deny"
inconsistent_struct_constructor = "warn"
imprecise_flops = "deny"
implicit_clone = "warn"
if_then_some_else_none = "warn"
if_not_else = "warn"
get_unwrap = "warn"
from_iter_instead_of_collect = "warn"
format_push_string = "warn"
format_collect = "warn"
fn_to_numeric_cast_any = "deny"
float_cmp_const = "deny"
float_cmp = "deny"
float_arithmetic = "warn"
flat_map_option = "warn"
filter_map_next = "warn"
filetype_is_file = "deny"
explicit_iter_loop = "warn"
explicit_into_iter_loop = "warn"
explicit_deref_methods = "warn"
equatable_if_let = "warn"
enum_glob_use = "warn"
empty_structs_with_brackets = "warn"
empty_enum_variants_with_brackets = "warn"
empty_drop = "warn"
elidable_lifetime_names = "warn"
doc_link_with_quotes = "warn"
doc_link_code = "warn"
doc_include_without_cfg = "warn"
disallowed_script_idents = "warn"
derive_partial_eq_without_eq = "warn"
deref_by_slicing = "warn"
default_numeric_fallback = "warn"
dbg_macro = "deny"
comparison_chain = "warn"
collection_is_never_read = "warn"
cloned_instead_of_copied = "warn"
clear_with_drain = "warn"
cfg_not_test = "warn"
cast_sign_loss = "deny"
cast_precision_loss = "deny"
cast_possible_wrap = "deny"
case_sensitive_file_extension_comparisons = "warn"
branches_sharing_code = "warn"
bool_to_int_with_if = "warn"
assigning_clones = "warn"
as_underscore = "warn"
type_complexity = "allow"