[tools]
rust = { version = "1.85.0", profile = "default", components = "rustfmt,rust-src,rust-analyzer" }
sccache = "0.15.0"

[env]
RUSTC_WRAPPER = { value = "sccache", os = ["linux", "macos"] }

[tasks.check]
description = "Run checks for formatting and linting (ensures locked and all features)"
shell = "bash -c"
run = [
  "cargo fmt --check",
  'CARGO_TARGET={{option(name="target")}} cargo clippy --locked --all-features ${CARGO_TARGET:+--features "$CARGO_TARGET"}',
]

[tasks.test]
description = "Run integration, doc, and other tests (ensures locked and all features)"
shell = "bash -c"
run = """
CARGO_TARGET={{option(name="target")}} cargo test \
    --locked \
    --all-features \
    ${CARGO_TARGET:+--features "$CARGO_TARGET"} \
    {{arg(name="test_name", var = true, default = "")}}
"""

[tasks.bench]
description = "Run benchmarks (ensures locked and all features)"
shell = "bash -c"
run = """
CARGO_TARGET={{option(name="target")}} cargo bench \
    --locked \
    --all-features \
    ${CARGO_TARGET:+--features "$CARGO_TARGET"} \
    {{arg(name="bench_name", var = true, default = "")}}
"""

[tasks.build]
description = "Build with release optimatizations (ensures locked all features)"
shell = "bash -c"
run = """
CARGO_TARGET={{option(name="target")}} cargo build \
    --locked \
    --all-features \
    ${CARGO_TARGET:+--features "$CARGO_TARGET"}
"""

[settings]
experimental = true
lockfile = true
