[tools]
rust = { version = "1.85.0", profile = "default", components = "rustfmt,rust-src,rust-analyzer" }
sccache = "0.15.0"

[env]
RUSTC_WRAPPER = "{% if os() != 'windows' %}sccache{% endif %}"

[tasks.check]
description = "Run checks for formatting and linting"
shell = "bash -c"
run = [
  "cargo fmt --check",
  'F={{option(name="features")}} T={{option(name="target")}} cargo clippy --locked ${F:+--features "$F"} ${T:+--target "$T"}',
]

[tasks.test]
description = "Run integration, doc, and other tests"
shell = "bash -c"
run = """
F={{option(name="features")}} T={{option(name="target")}} cargo test \
    --locked \
    ${F:+--features "$F"} \
    ${T:+--target "$T"} \
    {{arg(name="test_name", var = true, default = "")}}
"""

[tasks.bench]
description = "Run benchmarks"
shell = "bash -c"
run = """
F={{option(name="features")}} T={{option(name="target")}} cargo bench \
    --locked \
    ${F:+--features "$F"} \
    ${T:+--target "$T"} \
    {{arg(name="bench_name", var = true, default = "")}}
"""

[tasks.build]
description = "Build with release optimizations"
shell = "bash -c"
run = """
F={{option(name="features")}} T={{option(name="target")}} cargo build \
    --locked \
    ${F:+--features "$F"} \
    ${T:+--target "$T"}
"""

[settings]
experimental = true
lockfile = true
