[tools]
rust = { version = "1.85.0", profile = "default", components = "rustfmt,rust-src,rust-analyzer" }

[tools."github:mozilla/sccache"]
version = "0.15.0"

[tools."github:mozilla/sccache".platforms]
linux-x64     = { asset_pattern = "sccache-v*-x86_64-unknown-linux-musl.tar.gz" }
linux-arm64   = { asset_pattern = "sccache-v*-aarch64-unknown-linux-musl.tar.gz" }
macos-x64     = { asset_pattern = "sccache-v*-x86_64-apple-darwin.tar.gz" }
macos-arm64   = { asset_pattern = "sccache-v*-aarch64-apple-darwin.tar.gz" }
windows-x64   = { asset_pattern = "sccache-v*-x86_64-pc-windows-msvc.zip" }
windows-arm64 = { asset_pattern = "sccache-v*-aarch64-pc-windows-msvc.zip" }

[env]
RUSTC_WRAPPER = "{% if os() != 'windows' %}sccache{% endif %}"

[tasks.check]
description = "Run checks for formatting and linting"
shell = "bash -c"
usage = """
flag "--target <target>"
flag "--features <features>" default="default"
"""
run = ["cargo fmt --check", """
    cargo clippy \
        --locked \
        --all-targets \
        --no-default-features \
        ${usage_features:+--features "$usage_features"} \
        ${usage_target:+--target "$usage_target"}
    """]

[tasks.test]
description = "Run integration, doc, and other tests"
shell = "bash -c"
usage = """
flag "--target <target>"
flag "--features <features>" default="default"
arg "[test_name]" var=#true
"""
run = """
cargo test \
    --locked \
    --no-default-features \
    ${usage_features:+--features "$usage_features"} \
    ${usage_target:+--target "$usage_target"} \
    ${usage_test_name:-}
"""

[tasks.bench]
description = "Run benchmarks"
shell = "bash -c"
usage = """
flag "--target <target>"
flag "--features <features>" default="default"
arg "[bench_name]" var=#true
"""
run = """
cargo bench \
    --locked \
    --no-default-features \
    ${usage_features:+--features "$usage_features"} \
    ${usage_target:+--target "$usage_target"} \
    ${usage_bench_name:-}
"""

[tasks.build]
description = "Build with release optimizations"
shell = "bash -c"
usage = """
flag "--target <target>"
flag "--features <features>" default="default"
"""
run = """
cargo build \
    --locked \
    --no-default-features \
    ${usage_features:+--features "$usage_features"} \
    ${usage_target:+--target "$usage_target"}
"""

[settings]
experimental = true
lockfile = true
